### ISSUE TITLE
Server panic upon syncing notes with attachments?

### ISSUE THREAD

**Issue by mhoffmann75** [leanote/leanote#367]
I'm trying to run latest leanote binary on ubuntu 16.04 and it works so far. I had followed the install tutorial.

However as soon as i try to sync a note that i add a picture to (via iPhone app or mac OS X desktop client) these pictures don't sync and i get this server panic in leanote's log:

2016/05/31 18:25:29 server.go:2161: http: panic serving 192.168.250.103:56093: runtime error: invalid memory address or nil pointer dereference
goroutine 241 [running]:
net/http.(*conn).serve.func1(0xc82056f880)
	/Users/life/app/go1.6.2/src/net/http/server.go:1389 +0xc1
panic(0xc279e0, 0xc82000e0c0)
	/Users/life/app/go1.6.2/src/runtime/panic.go:443 +0x4e9
github.com/revel/revel.handleInvocationPanic(0xc8204a3ad0, 0xaba2e0, 0xc82063fac0)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/panic.go:30 +0x6a5
github.com/revel/revel.PanicFilter.func1(0xc8204a3ad0)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/panic.go:12 +0x53
panic(0xaba2e0, 0xc82063fac0)
	/Users/life/app/go1.6.2/src/runtime/panic.go:443 +0x4e9
github.com/revel/revel.InterceptorFilter.func1(0xc8204a3ad0)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/intercept.go:93 +0x6a
panic(0xaba2e0, 0xc82063fac0)
	/Users/life/app/go1.6.2/src/runtime/panic.go:443 +0x4e9
gopkg.in/mgo.v2/bson.ObjectIdHex(0x0, 0x0, 0x0, 0x0)
	/Users/life/Documents/Go/package_base/src/gopkg.in/mgo.v2/bson/bson.go:175 +0x210
github.com/leanote/leanote/app/service.(*GroupService).GetBelongToGroupIds(0x148a108, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/app/service/GroupService.go:158 +0xcc
github.com/leanote/leanote/app/service.(*GroupService).GetMineAndBelongToGroupIds(0x148a108, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/app/service/GroupService.go:85 +0x67
github.com/leanote/leanote/app/service.(*ShareService).getOrQ(0x148a108, 0x0, 0x0, 0xc8207462b8)
	/Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/app/service/ShareService.go:37 +0x49
github.com/leanote/leanote/app/service.(*ShareService).HasReadPerm(0x148a108, 0xc820430e20, 0x18, 0x0, 0x0, 0xc820430f20, 0x18, 0x0)
	/Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/app/service/ShareService.go:376 +0x45
github.com/leanote/leanote/app/service.(*FileService).GetFile(0x148a108, 0x0, 0x0, 0xc82064595e, 0x18, 0x0, 0x0)
	/Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/app/service/FileService.go:205 +0x64b
github.com/leanote/leanote/app/controllers/api.ApiFile.GetImage(0xc8204a3ad0, 0xc82064595e, 0x18, 0x0, 0x0)
	/Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/app/controllers/api/ApiFileController.go:64 +0xea
github.com/leanote/leanote/app/controllers/api.(*ApiFile).GetImage(0xc820572b20, 0xc82064595e, 0x18, 0x0, 0x0)
	<autogenerated>:217 +0xaf
reflect.Value.call(0xcfefc0, 0xc820572b20, 0x1e13, 0xd22280, 0x4, 0xc820433d20, 0x1, 0x1, 0x0, 0x0, ...)
	/Users/life/app/go1.6.2/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0xcfefc0, 0xc820572b20, 0x1e13, 0xc820433d20, 0x1, 0x1, 0x0, 0x0, 0x0)
	/Users/life/app/go1.6.2/src/reflect/value.go:303 +0xb1
github.com/revel/revel.ActionInvoker(0xc8204a3ad0, 0xc820346598, 0x0, 0x0)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/invoker.go:36 +0x4da
github.com/revel/revel.CompressFilter(0xc8204a3ad0, 0xc820346598, 0x1, 0x1)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/compress.go:47 +0xa2
github.com/revel/revel.InterceptorFilter(0xc8204a3ad0, 0xc820346590, 0x2, 0x2)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/intercept.go:103 +0x102
github.com/leanote/leanote/app/lea/i18n.I18nFilter(0xc8204a3ad0, 0xc820346588, 0x3, 0x3)
	/Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/app/lea/i18n/i18n.go:190 +0x2e5
github.com/revel/revel.ValidationFilter(0xc8204a3ad0, 0xc820346580, 0x4, 0x4)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/validation.go:191 +0x1d6
github.com/revel/revel.FlashFilter(0xc8204a3ad0, 0xc820346578, 0x5, 0x5)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/flash.go:46 +0x180
github.com/revel/revel.SessionFilter(0xc8204a3ad0, 0xc820346570, 0x6, 0x6)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/session.go:149 +0x135
github.com/revel/revel.ParamsFilter(0xc8204a3ad0, 0xc820346568, 0x7, 0x7)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/params.go:133 +0xbf
github.com/revel/revel.FilterConfiguringFilter(0xc8204a3ad0, 0xc820346560, 0x8, 0x8)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/filterconfig.go:208 +0x1fd
github.com/leanote/leanote/app/lea/route.RouterFilter(0xc8204a3ad0, 0xc820346558, 0x9, 0x9)
	/Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/app/lea/route/Route.go:86 +0x72d
github.com/revel/revel.PanicFilter(0xc8204a3ad0, 0xc820346550, 0xa, 0xa)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/panic.go:15 +0xa1
github.com/revel/revel.glob.func31(0xc8204a3ad0, 0xc820346548, 0xb, 0xb)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/watcher.go:232 +0x246
github.com/revel/revel.handleInternal(0x7f12d3b0fcd8, 0xc8205585b0, 0xc820412e00, 0x0)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/server.go:50 +0x3f3
github.com/revel/revel.handle(0x7f12d3b0fcd8, 0xc8205585b0, 0xc820412e00)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/server.go:38 +0x34f
net/http.HandlerFunc.ServeHTTP(0x1182b60, 0x7f12d3b0fcd8, 0xc8205585b0, 0xc820412e00)
	/Users/life/app/go1.6.2/src/net/http/server.go:1618 +0x3a
net/http.serverHandler.ServeHTTP(0xc82007ae00, 0x7f12d3b0fcd8, 0xc8205585b0, 0xc820412e00)
	/Users/life/app/go1.6.2/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc82056f880)
	/Users/life/app/go1.6.2/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/Users/life/app/go1.6.2/src/net/http/server.go:2137 +0x44e

Any idea where to look at - is it a bug?

**Comment by mhoffmann75** [comment]
After testing some more it seems to be reproducible this way:
Create a new note on leanote 2.0 for iPhone. Add a photo. Sync.
Now in leanote web (server 2.0) this is visible and everything seems ok.

Now open desktop client 2.0 on mac OS X. Sync. This note created on iOS syncs, but has broken picture. Upon opening note server drops aforementioned panic.

Same vice versa. It seems as if notes with pictures in them created on Desktop OSX and iPhone app are different and not compatible to each other. Although both are compatible to web leanote.
Any idea?? Very strange to me, maybe you get the clou?

Besides that notes created on OSX Desktop client containing larger photos (maybe 2MB or something) are never synced to leanote web. Despite of having set the upload file size limit in leanote admin to 0 or 99MB or something. But this may be a totally different story not related.

**Comment by mhoffmann75** [comment]
Finally solved. Long story short:
For all having sync problems with nginx, remember to add the following statement to your `nginx.conf`:

`client_max_body_size 20M;`

Adjust `20M` to whatever you specify as maximum image/attachment size (in Megabyte) in leanote. Otherwise nginx will silently stop larger notes from syncing.

It seems that ubuntu 14.04 comes with a different default value for `client_max_body_size` than ubuntu 16.04. :-) So its always safe to add this statement to force nginx to allow larger transfers.
Runs fine now on ubuntu 16.04 ...
