### ISSUE TITLE
backup & restore 之后图片无法正常显示, 添加

### ISSUE THREAD

**Issue by oliveagle** [leanote/leanote#370]
archlinux, mongodb 3.2.6-2, mongodb-tools 3.2.5-1
go version: 1.4.2

1. 设置好mongodb tool的位置, `/usr/bin/mongodump` , `/usr/bin/mongorestore`
2. 创建一篇带截图的markdown note.  
3. 备份
4. 删掉那一片笔记, 同时去存放图片的文件夹把图片移动成别的后缀. (本来想看看是不是连图片都备份了.)
5. restore
6. 去看恢复出来的笔记发现图片不能显示
7. 去存放图片的位置把图片恢复. (本以为这样就可以恢复正常了. ) 但是图片仍然不能显示. 
8. 重启服务几次都一样.  重新创建一篇新的笔记, 添加截图(ctrl+v)..  结果**新的笔记的图片也不能显示了**. 
另外, backup里边的所有备份记录也不翼而飞. 

![image](https://cloud.githubusercontent.com/assets/2270205/15803407/7a2b7320-2b0e-11e6-8d94-b09c04339671.png)

![image](https://cloud.githubusercontent.com/assets/2270205/15803410/a60a7e82-2b0e-11e6-9b53-190a73352e2c.png)

```

TRACE 2016/06/05 11:15:19 i18n.go:218: Unable to read locale cookie with name 'LEANOTE_LANG': http: named cookie not present
TRACE 2016/06/05 11:15:19 i18n.go:184: Found Accept-Language header value: en-US
2016/06/05 11:15:19 server.go:2161: http: panic serving 192.168.56.101:35552: runtime error: invalid memory address or nil pointer dereference
goroutine 288 [running]:
net/http.(*conn).serve.func1(0xc8203e8000)
	/Users/life/app/go1.6.2/src/net/http/server.go:1389 +0xc1
panic(0xc279e0, 0xc82000e0f0)
	/Users/life/app/go1.6.2/src/runtime/panic.go:443 +0x4e9
github.com/revel/revel.handleInvocationPanic(0xc82019c630, 0xaba2e0, 0xc8205abe50)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/panic.go:30 +0x6a5
github.com/revel/revel.PanicFilter.func1(0xc82019c630)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/panic.go:12 +0x53
panic(0xaba2e0, 0xc8205abe50)
	/Users/life/app/go1.6.2/src/runtime/panic.go:443 +0x4e9
github.com/revel/revel.InterceptorFilter.func1(0xc82019c630)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/intercept.go:93 +0x6a
panic(0xaba2e0, 0xc8205abe50)
	/Users/life/app/go1.6.2/src/runtime/panic.go:443 +0x4e9
gopkg.in/mgo.v2/bson.ObjectIdHex(0x0, 0x0, 0x0, 0x0)
	/Users/life/Documents/Go/package_base/src/gopkg.in/mgo.v2/bson/bson.go:175 +0x210
github.com/leanote/leanote/app/service.(*GroupService).GetBelongToGroupIds(0x148a108, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/app/service/GroupService.go:158 +0xcc
github.com/leanote/leanote/app/service.(*GroupService).GetMineAndBelongToGroupIds(0x148a108, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/app/service/GroupService.go:85 +0x67
github.com/leanote/leanote/app/service.(*ShareService).getOrQ(0x148a108, 0x0, 0x0, 0xc82060a2b8)
	/Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/app/service/ShareService.go:37 +0x49
github.com/leanote/leanote/app/service.(*ShareService).HasReadPerm(0x148a108, 0xc8206f5b60, 0x18, 0x0, 0x0, 0xc8206f5ba0, 0x18, 0x0)
	/Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/app/service/ShareService.go:376 +0x45
github.com/leanote/leanote/app/service.(*FileService).GetFile(0x148a108, 0x0, 0x0, 0xc820647d9e, 0x18, 0x0, 0x0)
	/Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/app/service/FileService.go:205 +0x64b
github.com/leanote/leanote/app/controllers/api.ApiFile.GetImage(0xc82019c630, 0xc820647d9e, 0x18, 0x0, 0x0)
	/Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/app/controllers/api/ApiFileController.go:64 +0xea
github.com/leanote/leanote/app/controllers/api.(*ApiFile).GetImage(0xc8202c8040, 0xc820647d9e, 0x18, 0x0, 0x0)
	<autogenerated>:217 +0xaf
reflect.Value.call(0xcfefc0, 0xc8202c8040, 0x1e13, 0xd22280, 0x4, 0xc8206f5880, 0x1, 0x1, 0x0, 0x0, ...)
	/Users/life/app/go1.6.2/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0xcfefc0, 0xc8202c8040, 0x1e13, 0xc8206f5880, 0x1, 0x1, 0x0, 0x0, 0x0)
	/Users/life/app/go1.6.2/src/reflect/value.go:303 +0xb1
github.com/revel/revel.ActionInvoker(0xc82019c630, 0xc82013a8f8, 0x0, 0x0)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/invoker.go:36 +0x4da
github.com/revel/revel.CompressFilter(0xc82019c630, 0xc82013a8f8, 0x1, 0x1)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/compress.go:47 +0xa2
github.com/revel/revel.InterceptorFilter(0xc82019c630, 0xc82013a8f0, 0x2, 0x2)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/intercept.go:103 +0x102
github.com/leanote/leanote/app/lea/i18n.I18nFilter(0xc82019c630, 0xc82013a8e8, 0x3, 0x3)
	/Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/app/lea/i18n/i18n.go:190 +0x2e5
github.com/revel/revel.ValidationFilter(0xc82019c630, 0xc82013a8e0, 0x4, 0x4)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/validation.go:191 +0x1d6
github.com/revel/revel.FlashFilter(0xc82019c630, 0xc82013a8d8, 0x5, 0x5)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/flash.go:46 +0x180
github.com/revel/revel.SessionFilter(0xc82019c630, 0xc82013a8d0, 0x6, 0x6)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/session.go:149 +0x135
github.com/revel/revel.ParamsFilter(0xc82019c630, 0xc82013a8c8, 0x7, 0x7)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/params.go:133 +0xbf
github.com/revel/revel.FilterConfiguringFilter(0xc82019c630, 0xc82013a8c0, 0x8, 0x8)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/filterconfig.go:208 +0x1fd
github.com/leanote/leanote/app/lea/route.RouterFilter(0xc82019c630, 0xc82013a8b8, 0x9, 0x9)
	/Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/app/lea/route/Route.go:86 +0x72d
github.com/revel/revel.PanicFilter(0xc82019c630, 0xc82013a8b0, 0xa, 0xa)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/panic.go:15 +0xa1
github.com/revel/revel.glob.func31(0xc82019c630, 0xc82013a8a8, 0xb, 0xb)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/watcher.go:232 +0x246
github.com/revel/revel.handleInternal(0x7fbbe6cd5958, 0xc82057e000, 0xc82012c0e0, 0x0)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/server.go:50 +0x3f3
github.com/revel/revel.handle(0x7fbbe6cd5958, 0xc82057e000, 0xc82012c0e0)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/server.go:38 +0x34f
net/http.HandlerFunc.ServeHTTP(0x1182b60, 0x7fbbe6cd5958, 0xc82057e000, 0xc82012c0e0)
	/Users/life/app/go1.6.2/src/net/http/server.go:1618 +0x3a
net/http.serverHandler.ServeHTTP(0xc8200aed80, 0x7fbbe6cd5958, 0xc82057e000, 0xc82012c0e0)
	/Users/life/app/go1.6.2/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc8203e8000)
	/Users/life/app/go1.6.2/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/Users/life/app/go1.6.2/src/net/http/server.go:2137 +0x44e
TRACE 2016/06/05 11:15:19 i18n.go:218: Unable to read locale cookie with name 'LEANOTE_LANG': http: named cookie not present
TRACE 2016/06/05 11:15:19 i18n.go:184: Found Accept-Language header value: en-US
2016/06/05 11:15:19 server.go:2161: http: panic serving 192.168.56.101:35554: runtime error: invalid memory address or nil pointer dereference
goroutine 321 [running]:
net/http.(*conn).serve.func1(0xc8203e8880)
	/Users/life/app/go1.6.2/src/net/http/server.go:1389 +0xc1
panic(0xc279e0, 0xc82000e0f0)
	/Users/life/app/go1.6.2/src/runtime/panic.go:443 +0x4e9
github.com/revel/revel.handleInvocationPanic(0xc82019c8f0, 0xaba2e0, 0xc8206e85d0)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/panic.go:30 +0x6a5
github.com/revel/revel.PanicFilter.func1(0xc82019c8f0)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/panic.go:12 +0x53
panic(0xaba2e0, 0xc8206e85d0)
	/Users/life/app/go1.6.2/src/runtime/panic.go:443 +0x4e9
github.com/revel/revel.InterceptorFilter.func1(0xc82019c8f0)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/intercept.go:93 +0x6a
panic(0xaba2e0, 0xc8206e85d0)
	/Users/life/app/go1.6.2/src/runtime/panic.go:443 +0x4e9
gopkg.in/mgo.v2/bson.ObjectIdHex(0x0, 0x0, 0x0, 0x0)
	/Users/life/Documents/Go/package_base/src/gopkg.in/mgo.v2/bson/bson.go:175 +0x210
github.com/leanote/leanote/app/service.(*GroupService).GetBelongToGroupIds(0x148a108, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/app/service/GroupService.go:158 +0xcc
github.com/leanote/leanote/app/service.(*GroupService).GetMineAndBelongToGroupIds(0x148a108, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/app/service/GroupService.go:85 +0x67
github.com/leanote/leanote/app/service.(*ShareService).getOrQ(0x148a108, 0x0, 0x0, 0xc82062a2b8)
	/Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/app/service/ShareService.go:37 +0x49
github.com/leanote/leanote/app/service.(*ShareService).HasReadPerm(0x148a108, 0xc8206e2380, 0x18, 0x0, 0x0, 0xc8206e23c0, 0x18, 0x0)
	/Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/app/service/ShareService.go:376 +0x45
github.com/leanote/leanote/app/service.(*FileService).GetFile(0x148a108, 0x0, 0x0, 0xc82066131e, 0x18, 0x0, 0x0)
	/Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/app/service/FileService.go:205 +0x64b
github.com/leanote/leanote/app/controllers/api.ApiFile.GetImage(0xc82019c8f0, 0xc82066131e, 0x18, 0x0, 0x0)
	/Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/app/controllers/api/ApiFileController.go:64 +0xea
github.com/leanote/leanote/app/controllers/api.(*ApiFile).GetImage(0xc8202c8078, 0xc82066131e, 0x18, 0x0, 0x0)
	<autogenerated>:217 +0xaf
reflect.Value.call(0xcfefc0, 0xc8202c8078, 0x1e13, 0xd22280, 0x4, 0xc820451200, 0x1, 0x1, 0x0, 0x0, ...)
	/Users/life/app/go1.6.2/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0xcfefc0, 0xc8202c8078, 0x1e13, 0xc820451200, 0x1, 0x1, 0x0, 0x0, 0x0)
	/Users/life/app/go1.6.2/src/reflect/value.go:303 +0xb1
github.com/revel/revel.ActionInvoker(0xc82019c8f0, 0xc82013a8f8, 0x0, 0x0)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/invoker.go:36 +0x4da
github.com/revel/revel.CompressFilter(0xc82019c8f0, 0xc82013a8f8, 0x1, 0x1)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/compress.go:47 +0xa2
github.com/revel/revel.InterceptorFilter(0xc82019c8f0, 0xc82013a8f0, 0x2, 0x2)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/intercept.go:103 +0x102
github.com/leanote/leanote/app/lea/i18n.I18nFilter(0xc82019c8f0, 0xc82013a8e8, 0x3, 0x3)
	/Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/app/lea/i18n/i18n.go:190 +0x2e5
github.com/revel/revel.ValidationFilter(0xc82019c8f0, 0xc82013a8e0, 0x4, 0x4)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/validation.go:191 +0x1d6
github.com/revel/revel.FlashFilter(0xc82019c8f0, 0xc82013a8d8, 0x5, 0x5)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/flash.go:46 +0x180
github.com/revel/revel.SessionFilter(0xc82019c8f0, 0xc82013a8d0, 0x6, 0x6)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/session.go:149 +0x135
github.com/revel/revel.ParamsFilter(0xc82019c8f0, 0xc82013a8c8, 0x7, 0x7)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/params.go:133 +0xbf
github.com/revel/revel.FilterConfiguringFilter(0xc82019c8f0, 0xc82013a8c0, 0x8, 0x8)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/filterconfig.go:208 +0x1fd
github.com/leanote/leanote/app/lea/route.RouterFilter(0xc82019c8f0, 0xc82013a8b8, 0x9, 0x9)
	/Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/app/lea/route/Route.go:86 +0x72d
github.com/revel/revel.PanicFilter(0xc82019c8f0, 0xc82013a8b0, 0xa, 0xa)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/panic.go:15 +0xa1
github.com/revel/revel.glob.func31(0xc82019c8f0, 0xc82013a8a8, 0xb, 0xb)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/watcher.go:232 +0x246
github.com/revel/revel.handleInternal(0x7fbbe6cd5958, 0xc82057e340, 0xc82024d960, 0x0)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/server.go:50 +0x3f3
github.com/revel/revel.handle(0x7fbbe6cd5958, 0xc82057e340, 0xc82024d960)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/server.go:38 +0x34f
net/http.HandlerFunc.ServeHTTP(0x1182b60, 0x7fbbe6cd5958, 0xc82057e340, 0xc82024d960)
	/Users/life/app/go1.6.2/src/net/http/server.go:1618 +0x3a
net/http.serverHandler.ServeHTTP(0xc8200aed80, 0x7fbbe6cd5958, 0xc82057e340, 0xc82024d960)
	/Users/life/app/go1.6.2/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc8203e8880)
	/Users/life/app/go1.6.2/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/Users/life/app/go1.6.2/src/net/http/server.go:2137 +0x44e
```

**Comment by oliveagle** [comment]
用命令行restore仍然是这个结果:
1. 关闭server.  手动drop掉leanote 数据库
2. 图片文件都是完好的. 
3. 手动重新导入备份的数据. 
4. 图片仍然不能显示. 仍然报相同的错.

**Comment by oliveagle** [comment]
用源码跑了发现: `userID` 是空的. 重新登录就正常了. 

提议:  userID 空的 或者其他没有权限的情况需要把用户自动登出?

另外. backup & restore 列表仍然是空的.

**Comment by lealife** [comment]
附件/图片不会备份, 这只会备份数据庫. 请手动备份

**Comment by Noevil0** [comment]
> 附件/图片不会备份，这只会备份数据库。请手动备份

你好，请问leanote的头像文件以及图片附件等需要手动备份的文件在那个文件夹呢？请告知谢谢！
