### ISSUE TITLE
panic: no reachable servers

### ISSUE THREAD

**Issue by zhengxiaopeng** [leanote/leanote#524]
突然挂了:

```bash
panic: no reachable servers

goroutine 1 [running]:
panic(0xa15900, 0xc420181c30)
	/Users/life/app/go1.7/src/runtime/panic.go:500 +0x1a1
github.com/leanote/leanote/app/db.Init(0xc420278ba0, 0x21, 0x0, 0x0)
	/Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/app/db/Mgo.go:104 +0x48cb
github.com/leanote/leanote/app.init.1.func28()
	/Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/app/init.go:423 +0x49
github.com/revel/revel.runStartupHooks()
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/server.go:164 +0x8e
github.com/revel/revel.InitServer(0xa961e0)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/server.go:85 +0x34
github.com/revel/revel.Run(0x0)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/server.go:137 +0x220
main.main()
	/Users/life/Desktop/leanote/leanote-public/app/tmp/main.go:2304 +0x2305d
```

**Comment by lealife** [comment]
请检查Mongodb是否启动正常

**Comment by liboyue23** [comment]
我也遇到同样的问题
INFO  2017/05/22 12:39:12 Debug.go:10: mongodb://127.0.0.1:27017/leanote
panic: no reachable servers

goroutine 1 [running]:
panic(0xa16a00, 0xc420199bf0)
	/Users/life/app/go1.7/src/runtime/panic.go:500 +0x1a1
github.com/leanote/leanote/app/db.Init(0xc42016b320, 0x21, 0x0, 0x0)
	/Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/app/db/Mgo.go:104 +0x48cb
github.com/leanote/leanote/app.init.1.func28()
	/Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/app/init.go:423 +0x49
github.com/revel/revel.runStartupHooks()
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/server.go:164 +0x8e
github.com/revel/revel.InitServer(0xa973e0)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/server.go:85 +0x34
github.com/revel/revel.Run(0x0)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/server.go:137 +0x220
main.main()
	/Users/life/Documents/kuaipan/leanote/leanote-public/app/tmp/main.go:2312 +0x23239

**Comment by wangxiaoyao** [comment]
我的修改了数据库leanote的密码。然后在leanote的app.conf 也对应修改后。就出现了这样情况。
1  当把mongo的auth：false 的时候，就可以连接上。已测！
2 进入mongo shell 。这个用户名密码也是没有问题的。已测！

```
panic: no reachable servers

goroutine 1 [running]:
github.com/leanote/leanote/app/db.Init(0xc420050320, 0x41, 0x0, 0x0)
        /usr/local/leanoted/gopackage/src/github.com/leanote/leanote/app/db/Mgo.go:104 +0x482c
github.com/leanote/leanote/app.init.1.func28()
        /usr/local/leanoted/gopackage/src/github.com/leanote/leanote/app/init.go:423 +0x49
github.com/revel/revel.runStartupHooks()
        /usr/leanoted/gopackage/src/github.com/revel/revel/server.go:164 +0x85
github.com/revel/revel.InitServer(0xb00440)
        /usr/leanoted/gopackage/src/github.com/revel/revel/server.go:85 +0x34
github.com/revel/revel.Run(0xb6a3)
        /usr/leanoted/gopackage/src/github.com/revel/revel/server.go:137 +0x1e4
main.main()
        /usr/local/leanoted/gopackage/src/github.com/leanote/leanote/app/tmp/main.go:2325 +0x24201
```

**Comment by dreampet** [comment]
@wangxiaoyao 我遇到了跟你一样的情况，后面发现是因为密码中带有"@"字符导致连接不上mongo服务器

**Comment by andyhuai** [comment]
我在导入数据时候,也出现这个问题,不知道怎么搞

**Comment by wangxiaoyao** [comment]
@andyhuai 请详细罗列你的步骤和细节，以及代码问题的提示

**Comment by andyhuai** [comment]
@wangxiaoyao ,
2018-01-22T02:09:35.862+0000	Failed: error connecting to db server: no reachable servers
我是安装下面这个链接来做的,
https://www.jianshu.com/p/58a999ccb32e,
在执行docker-compose run --rm initdb 时候报错

**Comment by wangxiaoyao** [comment]
@andyhuai 
1 我没有使用docker容器进行安装部署  。
2 我使用的是源码 进行部署安装 ：详见我的博客总结的相关问题： 希望对你有帮助。
http://blog.wangxiaoyao.com/2017/03/29/17-3-29leanote%E7%9A%84%E7%8E%A9%E6%B3%95/

http://blog.wangxiaoyao.com/2017/03/29/17-3-29mongodb/

**Comment by andyhuai** [comment]
@wangxiaoyao 
刚刚我又试试直接用二进制版本运行,恢复默认数据库出问题了
----------
> show dbs
local  0.078GB
> mongorestore -h localhost -d leanote --dir /volume1/boot/leanote/mongodb_backup/leanote_install_data/
2018-01-22T11:17:17.830+0800 E QUERY    SyntaxError: Unexpected identifier
>
--------------

是我的路径不对吗? MongoDB已经启动并且已经连接了

**Comment by happytoTom** [comment]
遇上了同样的问题，因为密码中带有"@"字符导致连接不上mongo服务器。。

**Comment by boostbob** [comment]
升级到 go 1.12 后出现此问题，MongoDB 服务器连接、参数、设置都OK，降级到 go 1.11 正常。

**Comment by jinchunguang** [comment]
高并发的时候，很容易出现这个，mongo 连接不够用

**Comment by realguan** [comment]
> @wangxiaoyao 我遇到了跟你一样的情况，后面发现是因为密码中带有"@"字符导致连接不上mongo服务器

感谢，我就是密码带了 @ 导致连接不上，一脸懵逼，改了密码终于好了
