### ISSUE TITLE
客户端所有图片无法正常显示

### ISSUE THREAD

**Issue by xueluofeng** [leanote/leanote#615]
windows,linux下客户端均无法显示任何手机APP或网页端添加的图片，只能显示本地添加的，而且当本地图片改变路径后也不会显示图片，个人环境如下，leanote端口号9001，site.url=http://xxxx.xxx.com，nginx代理80和443，服务器err log 如下：
2017/05/26 11:24:30 server.go:2317: http: panic serving 110.10.176.148:35486: runtime error: invalid memory address or nil pointer dereference
goroutine 1552 [running]:
net/http.(*conn).serve.func1(0xc4205b1c80)
	/Users/life/app/go1.7/src/net/http/server.go:1491 +0x12a
panic(0xa24aa0, 0xc420012090)
	/Users/life/app/go1.7/src/runtime/panic.go:458 +0x243
github.com/revel/revel.handleInvocationPanic(0xc420409550, 0x9f4200, 0xc4205d6f90)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/panic.go:30 +0x104
github.com/revel/revel.PanicFilter.func1(0xc420409550)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/panic.go:12 +0x5c
panic(0x9f4200, 0xc4205d6f90)
	/Users/life/app/go1.7/src/runtime/panic.go:458 +0x243
github.com/revel/revel.InterceptorFilter.func1(0xc420409550)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/intercept.go:93 +0x7d
panic(0x9f4200, 0xc4205d6f90)
	/Users/life/app/go1.7/src/runtime/panic.go:458 +0x243
gopkg.in/mgo.v2/bson.ObjectIdHex(0x0, 0x0, 0x0, 0x0)
	/Users/life/Documents/Go/package_base/src/gopkg.in/mgo.v2/bson/bson.go:175 +0x17f
github.com/leanote/leanote/app/service.(*GroupService).GetBelongToGroupIds(0xeb47c8, 0x0, 0x0, 0x9, 0xc42020b8a8, 0xc4204bc6d8)
	/Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/app/service/GroupService.go:158 +0xa7
github.com/leanote/leanote/app/service.(*GroupService).GetMineAndBelongToGroupIds(0xeb47c8, 0x0, 0x0, 0x8, 0x440d0e, 0xc4200ae820)
	/Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/app/service/GroupService.go:85 +0x5d
github.com/leanote/leanote/app/service.(*ShareService).getOrQ(0xeb47c8, 0x0, 0x0, 0xc4203b9a00)
	/Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/app/service/ShareService.go:37 +0x5c
github.com/leanote/leanote/app/service.(*ShareService).HasReadPerm(0xeb47c8, 0xc4203b9900, 0x18, 0x0, 0x0, 0xc4203b9a00, 0x18, 0x0)
	/Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/app/service/ShareService.go:376 +0x5a
github.com/leanote/leanote/app/service.(*FileService).GetFile(0xeb47c8, 0x0, 0x0, 0xc42051609e, 0x18, 0x28, 0xc420712d00)
	/Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/app/service/FileService.go:205 +0x4e3
github.com/leanote/leanote/app/controllers/api.ApiFile.GetImage(0xc420409550, 0xc42051609e, 0x18, 0x99d50c, 0xc420712cd8)
	/Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/app/controllers/api/ApiFileController.go:64 +0x91
github.com/leanote/leanote/app/controllers/api.(*ApiFile).GetImage(0xc42002a618, 0xc42051609e, 0x18, 0x0, 0x0)
	<autogenerated>:217 +0x66
reflect.Value.call(0xaafe60, 0xc42002a618, 0x1e13, 0xac0fd8, 0x4, 0xc4203b8e20, 0x1, 0x1, 0x9f4200, 0x9f4201, ...)
	/Users/life/app/go1.7/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0xaafe60, 0xc42002a618, 0x1e13, 0xc4203b8e20, 0x1, 0x1, 0x0, 0x1, 0xa1ec60)
	/Users/life/app/go1.7/src/reflect/value.go:302 +0xa4
github.com/revel/revel.ActionInvoker(0xc420409550, 0xc4204865f8, 0x0, 0x0)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/invoker.go:42 +0x670
github.com/revel/revel.CompressFilter(0xc420409550, 0xc4204865f8, 0x1, 0x1)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/compress.go:48 +0x90
github.com/revel/revel.InterceptorFilter(0xc420409550, 0xc4204865f0, 0x2, 0x2)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/intercept.go:103 +0xee
github.com/leanote/leanote/app/lea/i18n.I18nFilter(0xc420409550, 0xc4204865e8, 0x3, 0x3)
	/Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/app/lea/i18n/i18n.go:190 +0x28d
github.com/revel/revel.ValidationFilter(0xc420409550, 0xc4204865e0, 0x4, 0x4)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/validation.go:191 +0x166
github.com/revel/revel.FlashFilter(0xc420409550, 0xc4204865d8, 0x5, 0x5)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/flash.go:46 +0x132
github.com/revel/revel.SessionFilter(0xc420409550, 0xc4204865d0, 0x6, 0x6)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/session.go:149 +0x129
github.com/revel/revel.ParamsFilter(0xc420409550, 0xc4204865c8, 0x7, 0x7)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/params.go:133 +0xb2
github.com/revel/revel.FilterConfiguringFilter(0xc420409550, 0xc4204865c0, 0x8, 0x8)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/filterconfig.go:208 +0x128
github.com/leanote/leanote/app/lea/route.RouterFilter(0xc420409550, 0xc4204865b8, 0x9, 0x9)
	/Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/app/lea/route/Route.go:86 +0x367
github.com/revel/revel.PanicFilter(0xc420409550, 0xc4204865b0, 0xa, 0xa)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/panic.go:15 +0x94
github.com/revel/revel.glob..func31(0xc420409550, 0xc4204865a8, 0xb, 0xb)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/watcher.go:214 +0x7a
github.com/revel/revel.handleInternal(0xe71120, 0xc42022edd0, 0xc4205b7860, 0x0)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/server.go:55 +0x3ca
github.com/revel/revel.handle(0xe71120, 0xc42022edd0, 0xc4205b7860)
	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/server.go:39 +0x198
net/http.HandlerFunc.ServeHTTP(0xbac0e0, 0xe71120, 0xc42022edd0, 0xc4205b7860)
	/Users/life/app/go1.7/src/net/http/server.go:1726 +0x44
net/http.serverHandler.ServeHTTP(0xc420011080, 0xe71120, 0xc42022edd0, 0xc4205b7860)
	/Users/life/app/go1.7/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc4205b1c80, 0xe719a0, 0xc420516000)
	/Users/life/app/go1.7/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/Users/life/app/go1.7/src/net/http/server.go:2293 +0x44d

**Comment by xueluofeng** [comment]
非常感谢帮助，已经解决了，原因是在~/conf/app配置文件中site.url中附带了端口号
