### ISSUE TITLE
无法连接启用auth后的db

### ISSUE THREAD

**Issue by Chinese-Xu** [leanote/leanote#833]
mogodb 按文档方式启用了auth。设置防火墙端口开放后，远程mongodb客户端能正常使用用户名密码连接到leanote，服务器上也可以用mongo命令行+用户名密码登陆数据库

但是bash run.sh命令一直失败。切换回非auth后能正常连接。
还有其他地方能获得更多运行信息吗？

DEBUG 16:43:25  revel controller.go:523: RegisterController:Registered controller  section=controller controller=App\\memberuser 
DEBUG 16:43:25  revel server.go:106: InitServerEngine: Found server engine and invoking  section=server name=go 
panic: no reachable servers

goroutine 1 [running]:
github.com/leanote/leanote/app/db.Init(0xc420543e00, 0x2c, 0x0, 0x0)
	/Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/app/db/Mgo.go:104 +0x48c2
github.com/leanote/leanote/app.init.0.func28()
	/Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/app/init.go:423 +0x49
github.com/leanote/leanote/vendor/github.com/revel/revel.runStartupHooks()
	/Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/vendor/github.com/revel/revel/server.go:126 +0x7f
github.com/leanote/leanote/vendor/github.com/revel/revel.InitServer()
	/Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/vendor/github.com/revel/revel/server.go:37 +0x39
github.com/leanote/leanote/vendor/github.com/revel/revel.Run(0x0)
	/Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/vendor/github.com/revel/revel/server.go:69 +0xd4
main.main()
	/Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/app/tmp/main.go:2312 +0x223d5

**Comment by automaticdai** [comment]
app.conf配置了吗

**Comment by javaDer** [comment]
> 是否在app.conf配置了用户名和密码

app.conf 也配置的用户名和密码
就是不能启动

**Comment by javaDer** [comment]
我的已经解决啦,mongdb启动时需要加 --auth 参数
