### ISSUE TITLE
Hope support asciidoc

### ISSUE THREAD

**Issue by Aleishus** [leanote/leanote#849]
leanote is wonderful ！Hope support asciidoc. Thx

**Comment by helmut72** [comment]
Looks more like a dead project.

**Comment by Aleishus** [comment]
macos 10.14
java8
AsciidocFX 1.6.9
when typing emoji exception throws
```
ERROR => String index out of range: 2
java.lang.StringIndexOutOfBoundsException: String index out of range: 2
	at java.lang.String.substring(String.java:1963)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$null$358(GlassViewEventHandler.java:626)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleInputMethodEvent$359(GlassViewEventHandler.java:619)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleInputMethodEvent(GlassViewEventHandler.java:618)
	at com.sun.glass.ui.View.handleInputMethodEvent(View.java:647)
	at com.sun.glass.ui.View.notifyInputMethod(View.java:972)
	at com.sun.glass.ui.mac.MacView.notifyInputMethodMac(MacView.java:135)



```
