### ISSUE TITLE
源码构建失败

### ISSUE THREAD

**Issue by seaurching** [leanote/leanote#984]
使用源码蚂蚁笔记，出现错误。如何解决，内容如下：
```
CRIT  15:49:44  revel revel_logger.go:65: init: router initialize error             section=router error="Route validation error (in /root/leanote/conf/routes:8): revel/controller: failed to find action App\\index.default Stack: [utils.go router.go router.go router.go router.go router.go revel_hooks.go server.go server.go run.go main.go proc.go asm_amd64.s]"
CRIT  15:49:44  revel  server.go:68: Recovered error in startup                 error="init: router initialize error"
INFO  15:49:44  revel   event.go:46: Raising event                             section=util len=5
panic: init: router initialize error [recovered]
	panic: Fatal error in startup

goroutine 1 [running]:
github.com/revel/revel.Run.func1()
	/root/go/pkg/mod/github.com/revel/revel@v1.0.0/server.go:70 +0x12c
panic(0xa84d40, 0xc000389d50)
	/root/go/src/runtime/panic.go:965 +0x1b9
github.com/revel/revel/logger.(*RevelLogger).Panic(0xc000099220, 0xb7452e, 0x1d, 0xc0001c40a0, 0x2, 0x2)
	/root/go/pkg/mod/github.com/revel/revel@v1.0.0/logger/revel_logger.go:66 +0x9f
github.com/revel/revel.init.5.func1()
	/root/go/pkg/mod/github.com/revel/revel@v1.0.0/router.go:866 +0x228
github.com/revel/revel.RevelHooks.Run(0xc000122600, 0xb, 0x10)
	/root/go/pkg/mod/github.com/revel/revel@v1.0.0/revel_hooks.go:32 +0x1cc
github.com/revel/revel.InitServer()
	/root/go/pkg/mod/github.com/revel/revel@v1.0.0/server.go:39 +0x72
github.com/revel/revel.Run(0x8a72)
	/root/go/pkg/mod/github.com/revel/revel@v1.0.0/server.go:81 +0x165
github.com/leanote/leanote/app/tmp/run.Run(0x8a72)
	/root/leanote/app/tmp/run/run.go:32 +0x33
main.main()
	/root/leanote/app/tmp/main.go:24 +0xe5
Startup failure view previous messages,
 Proxy is listening : 8000
ERROR 15:49:44 harness.go:263: Could not start application              error="Revel Run Error (in starting your application there was an exception. Seeterminal output, exit status 2): "
```

**Comment by htmambo** [comment]
我编译倒是没问题，就是必须来回切换module
编译的时候开启：
```
go env -w GO111MODULE=on
```
运行的时候关闭
```
go env -w GO111MODULE=off

```

**Comment by lealife** [comment]
必须使用 go module
